export const REQUEST_FAILED = "REQUEST_FAILED";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_STARTED = "REQUEST_STARTED";
export const REQUEST_FINISHED = "REQUEST_FINISHED";

export const LOGIC_ERROR = "LOGIC_ERROR";
export const CLR_ERROR_STATE = "CLR_ERROR_STATE";