export const DO_REQUEST = "DO_USUARIO_REQUEST";
export const DO_REQUEST_BY_ID = "DO_USUARIO_REQUEST_BY_ID";

export const GET_REQUEST_SUCCESS = "GET_USUARIO_REQUEST_SUCCESS";
export const CLR_STATE = "CLR_USUARIO_STATE";

export const POST_REQUEST = "POST_USUARIO_REQUEST";
export const POST_REQUEST_SUCCESS = "POST_USUARIO_REQUEST_SUCCESS";